{
 "title": "OtusHWDashboard",
 "time": { "from": "2023-10-28T11:24:40.051Z", "to": "2023-10-28T11:35:10.994Z" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(http_response_time_seconds_count{path=\"/api/v1/user/1\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(response_status{path=\"/api/v1/user/1\", status=\"500\"}[1m])) by (method) / sum (rate(response_status{path=\"/api/v1/user/1\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(http_response_time_seconds_bucket{path=~\"/api/v1/user/1\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(http_response_time_seconds_bucket{path=~\"/api/v1/user/1\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(http_response_time_seconds_bucket{path=~\"/api/v1/user/1\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}